ja = open('README.ja.md', 'w')
ja.write('# ACR WASM テストサーバ\n\n')
ja.write('[English](README.md) | 日本語 | [Français](README.fr.md)\n\n')
ja.write('ACR（Across Report Renderer）のローカルプレビューサーバです。\n')
ja.write('Chrome拡張とWASMエンジンを使って、ブラウザ上で帳票をPNG形式で表示します。\n\n')
ja.write('## 必要な環境\n\n')
ja.write('- Google Chrome\n')
ja.write('- ACR Chrome拡張（無償）\n')
ja.write('- ライセンス登録: https://licensvr.acrossreport.com\n\n')
ja.write('## 使い方\n\n')
ja.write('```\n./acr-preview\nacr-preview.exe\n```\n\n')
ja.write('ブラウザが自動で開き http://localhost:7878 にアクセスします。\n\n')
ja.write('## お問い合わせ\n\n')
ja.write('- Web: https://acrossreport.com\n')
ja.write('- Mail: support@acrossreport.com\n')
ja.close()

fr = open('README.fr.md', 'w')
fr.write('# ACR WASM Serveur de test\n\n')
fr.write('[English](README.md) | [日本語](README.ja.md) | Français\n\n')
fr.write('Serveur de previsualisation locale pour ACR (Across Report Renderer).\n\n')
fr.write('## Environnement requis\n\n')
fr.write('- Google Chrome\n')
fr.write('- Extension Chrome ACR (gratuit)\n')
fr.write('- Inscription: https://licensvr.acrossreport.com\n\n')
fr.write('## Utilisation\n\n')
fr.write('```\n./acr-preview\nacr-preview.exe\n```\n\n')
fr.write('Le navigateur ouvre http://localhost:7878 automatiquement.\n\n')
fr.write('## Contact\n\n')
fr.write('- Web: https://acrossreport.com\n')
fr.write('- Mail: support@acrossreport.com\n')
fr.close()

print('Done')
